# Site settings
title: Qianqian Song
email: qsong@wakehealth.edu

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "/songqianqianlab.github.io" # the subpath of your site, e.g. /blog/

url: "songqianqianlab.github.io" # the base hostname & protocol for your site

twitter_username: Sophie_QSong
# github_username: github_username
linkedin_username: Qianqian Song
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
